# Generated by Django 4.0.10 on 2023-06-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosConcesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concesion', models.CharField(max_length=100)),
                ('tipo_concesion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('rs_ds', models.CharField(max_length=100)),
                ('tipo_tramite', models.CharField(max_length=100)),
                ('concesionario', models.CharField(max_length=100)),
                ('tipo_vigencia', models.CharField(max_length=100)),
            ],
        ),
    ]
