# Generated by Django 4.2.2 on 2023-06-21 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoCausa', models.CharField(max_length=1)),
                ('rol', models.CharField(max_length=20)),
                ('caratula', models.CharField(max_length=200)),
                ('nombreProyecto', models.CharField(max_length=200)),
                ('fechaSentencia', models.DateField()),
                ('descriptores', models.CharField(max_length=200)),
                ('linkSentencia', models.CharField(max_length=200)),
                ('urlSentencia', models.CharField(max_length=200)),
                ('activo', models.BooleanField()),
                ('tribunal', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=2)),
                ('relacionada', models.CharField(max_length=200)),
                ('visitas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idParametro', models.IntegerField()),
                ('idItemlista', models.IntegerField()),
                ('valor', models.CharField(blank=True, max_length=200, null=True)),
                ('parametro', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('jurisprudencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='JudicialSearch.jurisprudencia')),
            ],
        ),
    ]
