# Generated by Django 4.2.2 on 2023-06-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudicialSearch', '0002_alter_valor_iditemlista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudencia',
            name='caratula',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='descriptores',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='linkSentencia',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='nombreProyecto',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='relacionada',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='jurisprudencia',
            name='urlSentencia',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='valor',
            name='item',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='valor',
            name='parametro',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='valor',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
