# Generated by Django 4.0.10 on 2023-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JudicialSearch', '0004_alter_jurisprudencia_caratula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valor',
            name='item',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='valor',
            name='parametro',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='valor',
            name='valor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
